[METADATA]
modified = 2026-01-15T00:00:00Z
expires = 2027-01-15T00:00:00Z

[[ACCOUNTS]]
address = "r95GyZac4butvVcsTWUPpxzekmyzaHsTA5"
description = "Solus Protocol Issuing Address"

[[CURRENCIES]]
code = "SLS"
issuer = "r95GyZac4butvVcsTWUPpxzekmyzaHsTA5"
display_decimal = 2
symbol = "SLS"
logo_256x256 = "https://solusprotocol.com/logo.png"

[[PRINCIPALS]]
name = "Solus Protocol Team"
email = "support@solusprotocol.com"
